-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-04-22 21:58:52 ECT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




DROP TABLE ele_documentos CASCADE CONSTRAINTS ;

DROP TABLE ele_factura_detalles CASCADE CONSTRAINTS ;

DROP TABLE ele_factura_impuestos CASCADE CONSTRAINTS ;

CREATE TABLE ele_documentos
  (
    clave_acceso     VARCHAR2 (100) NOT NULL ,
    documento        VARCHAR2 (50) ,
    razon_social     VARCHAR2 (200) ,
    nombre_comercial VARCHAR2 (200) ,
    direccion        VARCHAR2 (200) ,
    establecimiento  VARCHAR2 (10) ,
    punto_emision    VARCHAR2 (10) ,
    secuencial       VARCHAR2 (10) ,
    fecha_emision    DATE ,
    autorizacion     VARCHAR2 (100) ,
    tipo             VARCHAR2 (10)
  ) ;
COMMENT ON TABLE ele_documentos
IS
  'En está tabla se guarda la cabecera del comprobante electronico' ;
ALTER TABLE ele_documentos ADD CONSTRAINT pk_ele_documentos PRIMARY KEY ( clave_acceso ) ;


CREATE TABLE ele_factura_detalles
  (
    clave_acceso_ele_documentos VARCHAR2 (100) NOT NULL ,
    numfila                     NUMBER NOT NULL ,
    codigo_principal            VARCHAR2 (50) ,
    descripcion                 VARCHAR2 (200) ,
    cantidad                    NUMBER ,
    precio_unitario             NUMBER ,
    descuento                   NUMBER ,
    precio_total_sin_impuesto   NUMBER ,
    codigo_articulo             VARCHAR2 (10) ,
    unidad_medida               VARCHAR2 (10) ,
    estado                      VARCHAR2 (10)
  ) ;
COMMENT ON TABLE ele_factura_detalles
IS
  'En está tabla se guarda el detalle de la factura electrónica' ;
ALTER TABLE ele_factura_detalles ADD CONSTRAINT pk_ele_factura_detalles PRIMARY KEY ( clave_acceso_ele_documentos, numfila ) ;


CREATE TABLE ele_factura_impuestos
  (
    clave_acceso_ele_documentos   VARCHAR2 (100) NOT NULL ,
    num_fila_ele_factura_detalles NUMBER NOT NULL ,
    num_fila                      NUMBER NOT NULL ,
    codigo                        VARCHAR2 (10) ,
    codigo_porcentaje             VARCHAR2 (10) ,
    tarifa                        NUMBER ,
    base_imponible                NUMBER ,
    valor                         NUMBER
  ) ;
COMMENT ON TABLE ele_factura_impuestos
IS
  'Tabla donde se guarda el detalle de los impuestos de cada detalle de la factura' ;
ALTER TABLE ele_factura_impuestos ADD CONSTRAINT pk_ele_factura_impuestos PRIMARY KEY ( clave_acceso_ele_documentos, num_fila_ele_factura_detalles, num_fila ) ;


ALTER TABLE ele_factura_detalles ADD CONSTRAINT fk_ele_documentos_detalles FOREIGN KEY ( clave_acceso_ele_documentos ) REFERENCES ele_documentos ( clave_acceso ) ON
DELETE CASCADE ;

ALTER TABLE ele_factura_impuestos ADD CONSTRAINT fk_ele_factura_impuestos_det FOREIGN KEY ( clave_acceso_ele_documentos, num_fila_ele_factura_detalles ) REFERENCES ele_factura_detalles ( clave_acceso_ele_documentos, numfila ) ON
DELETE CASCADE ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
